export const ROUTES = {
  home: '/',
  products: '/products',
  productDetail: (slug: string) => `/products/${slug}`,
  login: '/login',
  register: '/register',
  verifyEmail: '/verify-email',
  loginOtp: '/login-otp',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  cart: '/cart',
  checkout: '/checkout',
  orderSuccess: (orderId: string) => `/order-success/${orderId}`,
  orders: '/orders',
  orderDetail: (orderId: string) => `/orders/${orderId}`,
  profile: '/profile',
  addresses: '/addresses',
  wishlist: '/wishlist',
  notifications: '/notifications',
  about: '/about',
  contact: '/contact',
  privacyPolicy: '/privacy-policy',
  terms: '/terms',
  refundPolicy: '/refund-policy',
} as const
